#!/bin/bash

SERVER_URL="https://${CODESPACE_NAME}-7071.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
echo "Server URL: $SERVER_URL"

CLIENT_URL="https://${CODESPACE_NAME}-3000.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
echo "Client URL: $CLIENT_URL"

